In [2]:
import sys

sys.path.append(r"C:\Users\harsh\quactography")

from quactography.adj_matrix.io import load_graph
from qiskit.visualization import plot_distribution  # type: ignore
import numpy as np
import matplotlib.pyplot as plt
import nibabel as nib

In [17]:
solver = np.load('17_edges_rand_graph.npz',allow_pickle=True)
solver.files

['adjacency_matrix', 'node_indices', 'vol_dims']

In [18]:
print(solver['adjacency_matrix'])


[[0 1 1 1 0 0 0 0]
 [1 0 1 0 1 1 0 0]
 [1 1 0 1 1 1 1 0]
 [1 0 1 0 0 1 1 0]
 [0 1 1 0 0 1 0 1]
 [0 1 1 1 1 0 1 1]
 [0 0 1 1 0 1 0 1]
 [0 0 0 0 1 1 1 0]]


In [19]:

adjacency_matrix = solver['adjacency_matrix']
node_indices = solver['node_indices']
vol_dims = solver['vol_dims']
weighted_adjacency_matrix = np.where(adjacency_matrix == 1, np.random.uniform(0.01, 0.5, adjacency_matrix.shape), 0)

np.savez('weighted_17_edges_rand_graph.npz', adjacency_matrix=weighted_adjacency_matrix,node_indices=node_indices,
             vol_dims=vol_dims)


In [4]:
graph = np.load('all_test.npz', allow_pickle=True)
graph.files

['adjacency_matrix', 'node_indices', 'vol_dims']

In [5]:
print(graph['adjacency_matrix'])
print('\n')
print(graph['node_indices'])
print('\n')
print(graph['vol_dims'])

[[0. 1. 1. 1.]
 [1. 0. 2. 2.]
 [1. 2. 0. 2.]
 [1. 2. 2. 0.]]


[0 1 2 3]


[4 4]
