In [33]:
import numpy as np 
import sys

sys.path.append(r"C:\Users\harsh\quactography")

from quactography.graph.undirected_graph import Graph 
from quactography.adj_matrix.io import load_graph 

my_graph = load_graph("rand_graph.npz")
my_graph_class = Graph(my_graph[0], 1,3)
print(my_graph[0])
print(my_graph_class.starting_nodes)
print(my_graph_class.ending_nodes)
print(my_graph_class.weights)
print(my_graph_class.q_indices)

[[0. 3. 2. 3.]
 [3. 0. 2. 1.]
 [2. 2. 0. 3.]
 [3. 1. 3. 0.]]
[0, 0, 0, 1, 1, 2]
[1, 2, 3, 2, 3, 3]
[array([3., 2., 3., 2., 1., 3.])]
[0, 1, 2, 3, 4, 5]


#### En ce qui concerne l'Hamiltonien sur ce graphe en prenant les qubits comme étant les noeuds, on aurait le coût obligatoire: 

$$
    \sum_{<i,j>} w_{ij} (\frac{I-Z_i}{2}) (\frac{I-Z_j}{2})\\
    \ \frac{1}{4} \sum_{<i,j>} w_{ij} (I - Z_i - Z_j + Z_i Z_j)
    
$$



In [51]:
from qiskit.quantum_info import SparsePauliOp
pauli_weight_first_term = [
            ("I" * my_graph_class.number_of_edges, my_graph_class.all_weights_sum / 4)
        ]

for pos, node in enumerate(my_graph_class.ending_nodes):
    print(pos,node)
    str1 = (
        "I" * (my_graph_class.number_of_edges - 1 - node) + "Z" + "I" * node, 
        -my_graph_class.weights[0][pos]/4 
    )
    pauli_weight_first_term.append(str1)
for pos, node in enumerate(my_graph_class.starting_nodes):
    str2 = (
    "I" * (my_graph_class.number_of_edges - 1 - node) + "Z" + "I" * node, 
    -my_graph_class.weights[0][pos]/4 
    )
    pauli_weight_first_term.append(str2)
    
mandatory_cost_h = SparsePauliOp.from_list(pauli_weight_first_term)
mandatory_cost_h

0 1
1 2
2 3
3 2
4 3
5 3


SparsePauliOp(['IIIIII', 'IIIIZI', 'IIIZII', 'IIZIII', 'IIIZII', 'IIZIII', 'IIZIII', 'IIIIIZ', 'IIIIIZ', 'IIIIIZ', 'IIIIZI', 'IIIIZI', 'IIIZII'],
              coeffs=[ 3.5 +0.j, -0.75+0.j, -0.5 +0.j, -0.75+0.j, -0.5 +0.j, -0.25+0.j,
 -0.75+0.j, -0.75+0.j, -0.5 +0.j, -0.75+0.j, -0.5 +0.j, -0.25+0.j,
 -0.75+0.j])